config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: 'top#index'
  get 'top/index'
  resources :rooms
  resources :entries, only: [:new, :create, :destroy, :index], path: :rentals do
    post :confirm, on: :collection
    get :confirm_back, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :room
  scope :least_entries, ->(standard_date) { where(reserved_date: standard_date.to_date - 3.days .. standard_date.to_date + 3.days) }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  # validations
  validates :name, :place, :number, presence: true
  validates :name, length: { maximum: 30 }
  validates :place, inclusion: { in: ['東京', '大阪', '福岡', '札幌', '仙台', '名古屋', '金沢'] }
  validates :number, numericality: { less_than_or_equal_to: 5, more_than_or_equal_to: 30, }
  validates :name, format: { with: /\A\w+#\d{2}\z/, message: '会議室名が正しくありません' }
  validate :validate_number_of_people

  # callbacks
  before_validation :format_room_name

  private
  def validate_number_of_people
    unless self.number % 5 == 0
      self.errors[:number] << '収容人数は5の倍数で指定してください'
    end
  end

  def format_room_name
    trim_spaces_around_room_name if /\A\s+.+\s+\z/.match(self.name)
    remove_spaces_into_underscore_in_room_name if /(.+\s*)+/.match(self.name)
  end

  def trim_spaces_around_room_name
    self.name.strip!
  end

  def remove_spaces_into_underscore_in_room_name
    self.name.gsub!(/\s/, '_')
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ADMIN = { 'admin_user' => 'admin_password' }
  # before_action :authenticate

  private
  def authenticate
    authenticate_or_request_with_http_digest do |admin_username|
      ADMIN[admin_username]
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:destroy]
  def new
    @entry = Room.find(params[:room_id]).entries.new
  end

  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry.room, notice: "予約が完了しました。"}
        format.json { render :index, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entry.destroy
    respond_to do |format|
      # format.html { redirect_to room_path(@entry.room_id), notice: "予約を取り消しました。" }
      # format.json { head :no_content }
      format.js { head :no_content }
    end
  end

  def index
    @entries = Entry.all
  end

  def confirm
    @entry = Entry.new(entry_params)
    
    respond_to do |format|
      if @entry.valid?
        format.html { render 'confirm' }
        format.json { render json: :confirm }
      else
        format.html { redirect_to confirm_back_entries_path(entry: entry_params) }
      end
    end
  end

  def confirm_back
    @entry = Entry.new(entry_params)
    respond_to do |format|
      format.html { render :new, action: :new }
      format.json { render json: @book.errors, status: :unprocessable_entity }
    end
  end

  private
  def set_entry
    @entry = Entry.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:user_name, :user_email, :reserved_date, :usage_time, :room_id, :people)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        session[:room] = @room.name
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :place, :number)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    # TODO: トップページです。(適切なあいさつ文をビューに記載してください)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  layout 'users_header'

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_form.html.erb
<div class="field">
<%= form_with(model: entry, local: true, url: confirm_entries_path) do |f| %>
  <% if entry.errors.any?%>
    <div class="error_explanation">
      <p><%= pluralize(entry.errors.count, 'error') %>Prohibited this rental from being saved</p>
      <% entry.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
        </ul>
      <% end %>
    </div>
  <% end %>
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
    <%= f.label :reserved_date %>
    <%=f.date_field :reserved_date %>
    <%= f.label :usage_time %>
    <%=f.number_field :usage_time %>
    <%= f.label :people %>
    <%=f.number_field :people %>
    <%= f.hidden_field :room_id%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/confirm.html.erb
<h1>Entries#confirm</h1>
<p>Find me in app/views/entries/confirm.html.erb</p>

app/views/entries/create.html.erb
<h1>Entries#create</h1>
<p>Find me in app/views/entries/create.html.erb</p>

app/views/entries/index.html.erb
<h1>トップページ</h1>
<p><%= "==<会議室予約へようこそ>==" %></p>
<p><%=  "==<'希望の場所から会議室を選択できます!'>==" %></p>

app/views/entries/new.html.erb
<h1>会議室予約登録画面</h1>

<%= render 'form', entry: @entry %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to 'トップ', root_path %>
      <%= link_to '会議室登録', new_room_path %>
      <%= link_to '会議室一覧', rooms_path %>
    </header>
    <hr>
    <div class="main">
      <%= yield %>
    </div>
    <footer>
      © 2020 Copy Right Reserved Reservation
    </footer>
  </body>
</html>

app/views/layouts/users_header.html.erb
<%= link_to 'トップ', root_path %>
<%= link_to 'ユーザー登録', new_user_path %>

app/views/rooms/_entries.html.erb
<% rentals.each do |rental| %>
<table>
  <thead>
    <tr>
      <th>予約者</th>
      <th>予約日</th>
      <th>使用時間</th>
      <th>人数</th>
    </tr>
  </thead>
    <tbody>
    <tr>
      <td><%= rental.user_name %></td>
      <td><%= rental.reserved_date %></td>
      <td><%= rental.usage_time %></td>
      <td><%= rental.people %></td>
    </tr>
  </tbody>
</table>
<%= link_to '予約解除', rental, method: :delete, remote: true %>
<% end %>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<%= "最近登録した部屋: #{session[:room]} です。" if session[:room] %>
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>
<div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Place</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.place %></td>
        <td><%= room.number %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Room', new_room_path, id: 'new-room'%>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @room.place %>
</p>

<p>
  <strong>Number:</strong>
  <%= @room.number %>
</p>

<p><%= link_to '予約登録', new_entry_path(room_id: @room.id) %></p>

<%= render 'entries', rentals: @room.entries%>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/top/index.html.erb
<h1>予約管理のページへ　ようこそ</h1>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>